### ISSUE TITLE
Quality of life changes

### ISSUE THREAD

**Issue by STMiki** [CubicMC/cubic-server#117]
- [x] Add a simpler way to add a config entry
- [x] Logger - the code is... Well... Bad.
- [ ] Player.cpp file LOL (>1k lines)
- [x] Force quit when smashing ctrl + c multiple times
- [x] Remove `Global` from identifier in `types.hpp`
- [ ] Vector return reference on operator overlaod
- [x] Add logger level NETWORK and maybe DEV
- [ ] Improve call to Message
- [ ] Change where the soundSystem is tick
- [ ] Make all enum streamable
- [x] Add a common header file for define used everywhere
- [ ] Change the way the height map are calculated (do a new function set block without height map calculation and an other function update height maps)
- [ ] Rework some function naming (Player.cpp `playerPickupItem()`)

**Comment by STMiki** [comment]
For the `Player.cpp` I think there are parts that can be optimized (the registry *cough cough*). But most of the code are event handling, so we can reduce it a little, but not by much unfortunately

**Comment by huntears** [comment]
The registry is already planned to be reworked, but for the event handling I think that it is fine. Putting that stuff in other folders might just make the code less maintainable overall (Just a supposition).

**Comment by Trompettesib** [comment]
Sound System is ticked in the worldGroup running cycle

**Comment by Trompettesib** [comment]
Make all enum's streamable to be able to use them in the logger without having to cast everywhere.

**Comment by Trompettesib** [comment]
change where some define are to put them all in a specific file (like UNUSED who is in Server.hpp)
