### ISSUE TITLE
Server crash when clicking outside of the inventory with an empty hand

### ISSUE THREAD

**Issue by NekoSelena** [CubicMC/cubic-server#193]
When the inventory is open and the player left-click outside of the inventory box, this exception is thrown and the server crashes

![image](https://github.com/CubicMC/cubic-server/assets/62648027/209cb52f-abf7-402d-b30a-f253c6433dfc)

**Comment by huntears** [comment]
Somehow this triggers a DropButton screen event instead of a normal click, this is what is causing the crash, it should be pretty easy to fix this.
