### ISSUE TITLE
Embed JSON files inside the executable binary.

### ISSUE THREAD

**Issue by GamePlayer-8** [CubicMC/cubic-server#197]
Heyo,

There's an issue with the binary, since it requires `blocks-x.xx.x.json` & `registries-x.xx.x.json`, where `x.xx.x` is the actual Minecraft version.

How about embeding those config files inside the binary so the user / sysadmin musn't move them into the workdir too?

Eventually look for those files in `/usr/share/cubic-server` if the above solution is impossible.

**Comment by huntears** [comment]
Hello, thanks for the issue.

We are currently looking at how to achieve that properly since there are a lot of different ways to embed assets in a binary.
It looks like we would be going towards CMake trickeries but honestly this does not sound good so we are still looking.
