### ISSUE TITLE
Lack of cpp wrapper for the nbt lib

### ISSUE THREAD

**Issue by Trompettesib** [CubicMC/cubic-server#232]
For now it will stay like this, but an nbt json parsing is required if we want to parse some commands from mc.
So yes, this will happen, but when I have the time to make a cpp wrapper for the nbt lib

_Originally posted by @STMiki in https://github.com/CubicMC/cubic-server/pull/212#discussion_r1350088986_

**Comment by STMiki** [comment]
👋
