### ISSUE TITLE
Errors when playing Minosoft with CubicMC server

### ISSUE THREAD

**Issue by nitram84** [CubicMC/cubic-server#276]
I tried to play Minosoft (git version https://github.com/Bixilon/Minosoft/commit/bef2f861381cbdd997f8462ced3af98e3cba3ce0) with a local CubicMC server (latest git/0.4.0-beta release). After/during spawning I got the first stacktrace in Minosoft and a second happened when I tried to chop some oak leaves. I first reported these issues to Minosoft but the stacktraces were caused by two protocol issues in CubicMC. Please see the log files in https://github.com/Bixilon/Minosoft/issues/30 and the findings in https://github.com/Bixilon/Minosoft/issues/30#issuecomment-1951443073 .

**Steps to reproduce:**

- start Cubic server locally with `./CubicServer --online-mode false`
- use an offline account in Minosoft
- connect to local server with `Forced version: automatic` and `Releases [x]`. -> version 1.19.3 will be used
  -> first stacktrace should appear when all resources are loaded
- try to chop a tree, in my case oak leaves
  -> second stacktrace should appear in Minosoft log

To reproduce the issues it is important to test with the Minosoft version https://github.com/Bixilon/Minosoft/commit/bef2f861381cbdd997f8462ced3af98e3cba3ce0 . The next commit (https://github.com/Bixilon/Minosoft/commit/d88a08014a141748c7c489c69741fccef086992d) silences the first CubicMC protocol error.

**Comment by huntears** [comment]
Thank you for the bug report! I will fix that directly once at home :)

**Comment by emneo-dev** [comment]
Thank you for reporting those issues, we are currently in the process of rewriting the whole server, so I am not sure how long that fix will be useful for :)
