### ISSUE TITLE
Server exits when config file is missing a line

### ISSUE THREAD

**Issue by NekoSelena** [CubicMC/cubic-server#73]
If one of the required lines does not exist/is not filled out in the config file, the server stops with an exception thrown (and caught).
![image](https://user-images.githubusercontent.com/62648027/210246959-8972d30a-5c02-4186-ba9f-3b5a7486ad01.png)
It would be better if the line was created with a default value, or at least the thrown exception would specify the missing line for the user to add it by hand.

**Comment by STMiki** [comment]
Fixed in #141
